<?php

namespace AppBundle\Repository;

/**
 * AccountQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
