<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Question;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public static $alias = 'ans';
    
    public function getSortedForQuestion(Question $question) {
        $query = $this->createQueryBuilder(self::$alias)
                ->orderBy(self::$alias.'.orderNo')
                ->where(self::$alias.'.question=:question')
                ->setParameter('question', $question);
        
        $results = $query->getQuery()
                ->getResult();
        
        return $results;
    }
}
