admin_test_group:
    resource: "@AppBundle/Resources/config/routing/admin/test.yml"
    prefix:     /test
    
admin_question_group:
    resource: "@AppBundle/Resources/config/routing/admin/question.yml"
    prefix:     /pytanie
    
admin_answer_group:
    resource: "@AppBundle/Resources/config/routing/admin/answer.yml"
    prefix:     /odpowiedz
    
admin_index_group:
    resource: "@AppBundle/Resources/config/routing/admin/admin.yml"
    prefix:     /