test_index:
    path:     /
    defaults: { _controller: AppBundle:Test:index }
    
test_start:
    path:     /rozpocznij/{slug}
    defaults: { _controller: AppBundle:Test:start }
    
test_question:
    path:     /{slug}/pytanie/{questionNo}
    defaults: { _controller: AppBundle:Test:question,  questionNo: 1 }

test_rank:
    path:     /ranking
    defaults: { _controller: AppBundle:Test:rank,  questionNo: 1 }