-- MySQL Script generated by MySQL Workbench
-- wto, 6 gru 2016, 15:45:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema course
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema course
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `course` DEFAULT CHARACTER SET utf8 ;
USE `course` ;

-- -----------------------------------------------------
-- Table `course`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course`.`address` ;

CREATE TABLE IF NOT EXISTS `course`.`address` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NULL,
  `postcode` VARCHAR(6) NULL,
  `city` VARCHAR(255) NULL,
  `voivodeship` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `course`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course`.`account` ;

CREATE TABLE IF NOT EXISTS `course`.`account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `role` VARCHAR(255) NOT NULL DEFAULT '',
  `firstname` VARCHAR(60) NOT NULL DEFAULT '',
  `surname` VARCHAR(60) NOT NULL DEFAULT '',
  `id_address` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_account_address_idx` (`id_address` ASC),
  CONSTRAINT `fk_account_address`
    FOREIGN KEY (`id_address`)
    REFERENCES `course`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `course`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course`.`test` ;

CREATE TABLE IF NOT EXISTS `course`.`test` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_author` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `start` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_test_account_idx` (`id_author` ASC),
  CONSTRAINT `fk_test_account`
    FOREIGN KEY (`id_author`)
    REFERENCES `course`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

