admin_tag_index:
    path:     /
    defaults: { _controller: "AppBundle:Admin/Tag:index" }

admin_tag_add:
    path:     /dodaj
    defaults: { _controller: "AppBundle:Admin/Tag:add" }

admin_tag_edit:
    path:     /{id}/edytuj
    defaults: { _controller: "AppBundle:Admin/Tag:edit" }