admin_test_index:
    path:     /
    defaults: { _controller: "AppBundle:Admin/Test:index" }
    methods:  GET

admin_test_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin/Test:show" }
    methods:  GET

admin_test_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/Test:new" }
    methods:  [GET, POST]

admin_test_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/Test:edit" }
    methods:  [GET, POST]
    
admin_test_sort_questions:
    path:     /{id}/sort
    defaults: { _controller: "AppBundle:Admin/Test:sort" }
    methods:  [POST]

admin_test_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/Test:delete" }
    methods:  DELETE
