app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

logout:
    path: /logout

account_group:
    resource: "@AppBundle/Resources/config/routing/account.yml"
    prefix:     /
    
test_group:
    resource: "@AppBundle/Resources/config/routing/test.yml"
    prefix:     /test

article_group:
    resource: "@AppBundle/Resources/config/routing/article.yml"
    prefix:     /artykul


admin_group:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:     /admin