app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

account_group:
    resource: "@AppBundle/Resources/config/routing/account.yml"
    prefix:     /
    
admin_group:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:     /admin