AppBundle\Entity\Answer:
    type: entity
    table: answer
    repositoryClass: AppBundle\Repository\AnswerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: string
            length: '1024'     
        valid:
            type: boolean
        orderNo:
            type: integer
            column: order_no
            
    manyToOne:
        author:
            targetEntity: Account
            joinColumn: 
                name: id_author
                referencedColumnName: id
        question:
            targetEntity: Question
            inversedBy: answers
            joinColumn:
                name: id_question
                referencedColumnName: id
    lifecycleCallbacks: {  }
