AppBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: string
            length: '2048'
        created:
            type: datetime

    manyToOne:
        article:
            targetEntity: Article
            inversedBy: comments
            joinColumn:
                name: id_article
                referencedColumnName: id
        author:
            targetEntity: Account
            joinColumn:
                name: id_author
                referencedColumnName: id

    lifecycleCallbacks: {  }
